config: 64_01_100_bm_unet_01
root_dir: ./out/64_data_volume/64_01_100_bm_unet_01
model:
  name: unet
  parameters:
    in_channels: 1
    model_channels: 128
    out_channels: 1
    num_res_blocks: 2
    attention_resolutions: [2]
    dropout: 0
    channel_mult: [1, 2, 2, 2]
    conv_resample: true
    num_heads: 4
data:
  num_frames: 4
  train_dataset_dir: ./data/dataset_64_01/
  train_indices: [0, 1, 2, 3, 4]
  train_indices_range: [0, 100]
  train_batch_size: 32
  val_dataset_dir: ./data/dataset_64_01/
  val_indices: [5, 6]
  val_indices_range: [100, 150]
  val_batch_size: 32
  ensemble_dataset_dir: ./data/dataset_64_02_ensemble/
  ensemble_indices: [0]
  ensemble_indices_range: [0, 10]
  ensemble_batch_size: 32
train:
  checkpoint: false
  n_epochs: 100
  lr: 0.00001
  device: cuda
  log_file: "{{root_dir}}/logs/train.log"
  csv_file: "{{root_dir}}/logs/train.csv"
  checkpoint_dir: "{{root_dir}}/checkpoints"
  results_dir: "{{root_dir}}/results"
  checkpoint_interval: 100
  results_interval: 1
  val_interval: 1
  patience: 5
val:
  normal_val: false
  normal_val_interval: 1
  normal_val_metrics:
    MSE: {}
    PSNR: {}
    SSIM: {}
    Acc: 
      threshold: 0.2
    HR: {}
    CR: {}
    FID: {}
    KL: {}
  ensemble_val: true
  ensemble_val_interval: 1
  ensemble_val_metrics:
    MSE: {}
    PSNR: {}
    SSIM: {}
    Acc: 
      threshold: 0.2
    HR: {}
    CR: {}
    FID: {}
    KL: {}
  n_samples: 1